name: Kbot CI/CD

on:
  push:
    branches:
      - development
env:
  REGISTRY: ghcr.io/rublen/kbot
  SHORT_SHA: ${GITHUB_SHA::7}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run test
        run: make test

      - name: ghcr_auth
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build . --tag ${{ env.REGISTRY }}:v1.0.0-${{ env.SHORT_SHA }}-linux-amd64
        working-directory: .

      - name: Push image
        run: docker push ${{ env.REGISTRY }}:v1.0.0-${{ env.SHORT_SHA }}-linux-amd64
        permissions:
          contents: read
          packages: write
