name: Kbot CI/CD

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: k8s-k9s-kub
  REGION: europe-central2
  GAR_LOCATION: europe-central2-docker.pkg.dev/k8s-k9s-kub/kbot
  IMAGE_NAME: ${{ env.GAR_LOCATION }}:v1.0.3

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run test
        run: make test

      - name: gar_auth
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --tag ${{ env.IMAGE_NAME }}
        working-directory: WORKING_DIRECTORY

      - name: Push image
        run: docker push ${{ env.IMAGE_NAME }}
